<a href="https://colab.research.google.com/github/BilawalBaloch/Projects/blob/main/test_match_datacleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Test Match data cleaning and modeling**

**HERE is the list what we did**

1.   Importing important libr & excel file
2.   Looking for Null values sum , accordig to the columns
3.  Renaming NO to Not Out as given on website
4. Fillin For null vales
5. looking for duplicate and removing them
6. Spliytting country and players name
7. giving new names on 1 and 0 basies
8. Making two new columns out of one cloumn
9. Correcting data type

# *Importing important libr & excel file*

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_excel('/content/test.match.data.xlsx')
data.head(7)

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10.0,6996,334,99.94,9800+,58.60,29,13,7,626,6
1,AC Voges (AUS),2015-2016,20,31,7.0,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4.0,2256,274,60.97,1707+,54.48,7,11,1,246,11
3,GA Headley (WI),1930-1954,22,40,4.0,2190,270*,60.83,416+,56.00,10,5,2,104,1
4,H Sutcliffe (ENG),1924-1935,54,84,9.0,4555,194,60.73,6558+,34.59,16,23,2,202,6
5,HC Brook (ENG),2022-2024,15,24,1.0,1378,186,59.91,1520,90.65,5,8,1,164,25
6,E Paynter (ENG),1931-1939,20,31,5.0,1540,243,59.23,1288+,45.88,4,7,3,125,4

In [ ]:
data.tail(4)

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
58,GC Smith (ICC/SA),2002-2014,117,205,13.0,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4.0,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5.0,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6.0,1296,127,48.00,2110+,25.59,1,10,2,53,0

# **Looking for Null values sum , accordig to the columns**

---

In [ ]:
data.isnull().sum()

Player    0
Span      0
Mat       0
Inns      0
NO        1
Runs      0
HS        0
Ave       0
BF        2
SR        2
100       0
50        0
0         0
4s        0
6s        0
dtype: int64

**Renaming NO to Not Out as given on website**

In [ ]:
data.rename(columns={'NO':'Not_Out'}, inplace=True)

In [ ]:
data.rename(columns={'HS':'highest_score'}, inplace=True)

In [ ]:
data.rename(columns={'BF':'Ball_Faced'}, inplace=True)

In [ ]:
data.rename(columns={'SR':'Strike_Rate'}, inplace=True)

In [ ]:
data.rename(columns={'Span':'year_period'}, inplace=True)

In [ ]:
data

,Player,year_period,Mat,Inns,Not_Out,Runs,highest_score,Ave,Ball_Faced,Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10.0,6996,334,99.94,9800+,58.60,29,13,7,626,6
1,AC Voges (AUS),2015-2016,20,31,7.0,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4.0,2256,274,60.97,1707+,54.48,7,11,1,246,11
3,GA Headley (WI),1930-1954,22,40,4.0,2190,270*,60.83,416+,56.00,10,5,2,104,1
4,H Sutcliffe (ENG),1924-1935,54,84,9.0,4555,194,60.73,6558+,34.59,16,23,2,202,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14.0,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13.0,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4.0,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5.0,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6.0,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [ ]:
data.isnull().sum()

Player           0
year_period      0
Mat              0
Inns             0
Not_Out          1
Runs             0
highest_score    0
Ave              0
Ball_Faced       2
Strike_Rate      2
100              0
50               0
0                0
4s               0
6s               0
dtype: int64

In [ ]:
data.isnull().any()

Player           False
year_period      False
Mat              False
Inns             False
Not_Out           True
Runs             False
highest_score    False
Ave              False
Ball_Faced        True
Strike_Rate       True
100              False
50               False
0                False
4s               False
6s               False
dtype: bool

In [ ]:
data_dropna = data.dropna(how='all')
print(data_dropna)

               Player year_period  Mat  Inns  Not_Out  Runs highest_score  \
0    DG Bradman (AUS)   1928-1948   52    80     10.0  6996           334
1      AC Voges (AUS)   2015-2016   20    31      7.0  1485          269*
2     RG Pollock (SA)   1963-1970   23    41      4.0  2256           274
3     GA Headley (WI)   1930-1954   22    40      4.0  2190          270*
4   H Sutcliffe (ENG)   1924-1935   54    84      9.0  4555           194
..                ...         ...  ...   ...      ...   ...           ...
57   KD Walters (AUS)   1965-1981   74   125     14.0  5357           250
58  GC Smith (ICC/SA)   2002-2014  117   205     13.0  9265           277
59  WH Ponsford (AUS)   1924-1934   29    48      4.0  2122           266
60    SJ McCabe (AUS)   1930-1938   39    62      5.0  2748           232
61   DR Jardine (ENG)   1928-1934   22    33      6.0  1296           127

      Ave Ball_Faced  Strike_Rate  100  50   0    4s  6s
0   99.94      9800+        58.60   29  13   7   626   6
1   61.87       2667        55.68    5   4   2   186   5
2   60.97      1707+        54.48    7  11   1   246  11
3   60.83       416+        56.00   10   5   2   104   1
4   60.73      6558+        34.59   16  23   2   202   6
..    ...        ...          ...  ...  ..  ..   ...  ..
57  48.26      8662+        49.16   15  33   4   525  23
58  48.25      15525        59.67   27  38  11  1165  24
59  48.22      3118+        44.77    7   6   1   119   0
60  48.21      3217+        60.02    6  13   4   241   5
61  48.00      2110+        25.59    1  10   2    53   0

[62 rows x 15 columns]

# **Fillin For null vales**

In [ ]:
data['Ball_Faced'] = data['Ball_Faced'].fillna(method='ffill')
data['Strike_Rate'] = data['Strike_Rate'].fillna(method='bfill')
data['Not_Out'] = data['Not_Out'].fillna(method='bfill')

<ipython-input-491-3041b8f594ae>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['Ball_Faced'] = data['Ball_Faced'].fillna(method='ffill')
<ipython-input-491-3041b8f594ae>:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['Strike_Rate'] = data['Strike_Rate'].fillna(method='bfill')
<ipython-input-491-3041b8f594ae>:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['Not_Out'] = data['Not_Out'].fillna(method='bfill')

In [ ]:
data.isnull().sum()

Player           0
year_period      0
Mat              0
Inns             0
Not_Out          0
Runs             0
highest_score    0
Ave              0
Ball_Faced       0
Strike_Rate      0
100              0
50               0
0                0
4s               0
6s               0
dtype: int64

In [ ]:
#data['Ball_Faced'] = data['Ball_Faced'].fillna(data['Ball_Faced'])==1

In [ ]:
#data['Strike_Rate'] = data['Strike_Rate'].fillna(data['Strike_Rate'])==2

In [ ]:
#data['Not_Out'] = data['Not_Out'].fillna(data['Not_Out'])==3

# **looking for duplicate and removing them**

In [ ]:
data.duplicated().sum()

0

In [ ]:
data.drop_duplicates()

,Player,year_period,Mat,Inns,Not_Out,Runs,highest_score,Ave,Ball_Faced,Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10.0,6996,334,99.94,9800+,58.60,29,13,7,626,6
1,AC Voges (AUS),2015-2016,20,31,7.0,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4.0,2256,274,60.97,1707+,54.48,7,11,1,246,11
3,GA Headley (WI),1930-1954,22,40,4.0,2190,270*,60.83,416+,56.00,10,5,2,104,1
4,H Sutcliffe (ENG),1924-1935,54,84,9.0,4555,194,60.73,6558+,34.59,16,23,2,202,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14.0,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13.0,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4.0,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5.0,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6.0,1296,127,48.00,2110+,25.59,1,10,2,53,0

# **Spliytting country and players name**

In [ ]:
data['Player'].str.split(pat = '\(')

0      [DG Bradman , AUS)]
1        [AC Voges , AUS)]
2       [RG Pollock , SA)]
3       [GA Headley , WI)]
4     [H Sutcliffe , ENG)]
              ...
57     [KD Walters , AUS)]
58    [GC Smith , ICC/SA)]
59    [WH Ponsford , AUS)]
60      [SJ McCabe , AUS)]
61     [DR Jardine , ENG)]
Name: Player, Length: 62, dtype: object

**giving new names on 1 and 0 basies**

In [ ]:
data['country'] = data['Player'].str.split(pat = '\(').str[1]

In [ ]:
data

,Player,year_period,Mat,Inns,Not_Out,Runs,highest_score,Ave,Ball_Faced,Strike_Rate,100,50,0,4s,6s,country
0,DG Bradman (AUS),1928-1948,52,80,10.0,6996,334,99.94,9800+,58.60,29,13,7,626,6,AUS)
1,AC Voges (AUS),2015-2016,20,31,7.0,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS)
2,RG Pollock (SA),1963-1970,23,41,4.0,2256,274,60.97,1707+,54.48,7,11,1,246,11,SA)
3,GA Headley (WI),1930-1954,22,40,4.0,2190,270*,60.83,416+,56.00,10,5,2,104,1,WI)
4,H Sutcliffe (ENG),1924-1935,54,84,9.0,4555,194,60.73,6558+,34.59,16,23,2,202,6,ENG)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14.0,5357,250,48.26,8662+,49.16,15,33,4,525,23,AUS)
58,GC Smith (ICC/SA),2002-2014,117,205,13.0,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA)
59,WH Ponsford (AUS),1924-1934,29,48,4.0,2122,266,48.22,3118+,44.77,7,6,1,119,0,AUS)
60,SJ McCabe (AUS),1930-1938,39,62,5.0,2748,232,48.21,3217+,60.02,6,13,4,241,5,AUS)
61,DR Jardine (ENG),1928-1934,22,33,6.0,1296,127,48.00,2110+,25.59,1,10,2,53,0,ENG)

In [ ]:
data['players'] = data['Player'].str.split(pat = '\(').str[0]

In [ ]:
data

,Player,year_period,Mat,Inns,Not_Out,Runs,highest_score,Ave,Ball_Faced,Strike_Rate,100,50,0,4s,6s,country,players
0,DG Bradman (AUS),1928-1948,52,80,10.0,6996,334,99.94,9800+,58.60,29,13,7,626,6,AUS),DG Bradman
1,AC Voges (AUS),2015-2016,20,31,7.0,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS),AC Voges
2,RG Pollock (SA),1963-1970,23,41,4.0,2256,274,60.97,1707+,54.48,7,11,1,246,11,SA),RG Pollock
3,GA Headley (WI),1930-1954,22,40,4.0,2190,270*,60.83,416+,56.00,10,5,2,104,1,WI),GA Headley
4,H Sutcliffe (ENG),1924-1935,54,84,9.0,4555,194,60.73,6558+,34.59,16,23,2,202,6,ENG),H Sutcliffe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14.0,5357,250,48.26,8662+,49.16,15,33,4,525,23,AUS),KD Walters
58,GC Smith (ICC/SA),2002-2014,117,205,13.0,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA),GC Smith
59,WH Ponsford (AUS),1924-1934,29,48,4.0,2122,266,48.22,3118+,44.77,7,6,1,119,0,AUS),WH Ponsford
60,SJ McCabe (AUS),1930-1938,39,62,5.0,2748,232,48.21,3217+,60.02,6,13,4,241,5,AUS),SJ McCabe
61,DR Jardine (ENG),1928-1934,22,33,6.0,1296,127,48.00,2110+,25.59,1,10,2,53,0,ENG),DR Jardine

**droping the null coulmns**

In [ ]:
data.drop(columns=['Player'], inplace=True)

In [ ]:
data

,year_period,Mat,Inns,Not_Out,Runs,highest_score,Ave,Ball_Faced,Strike_Rate,100,50,0,4s,6s,country,players
0,1928-1948,52,80,10.0,6996,334,99.94,9800+,58.60,29,13,7,626,6,AUS),DG Bradman
1,2015-2016,20,31,7.0,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS),AC Voges
2,1963-1970,23,41,4.0,2256,274,60.97,1707+,54.48,7,11,1,246,11,SA),RG Pollock
3,1930-1954,22,40,4.0,2190,270*,60.83,416+,56.00,10,5,2,104,1,WI),GA Headley
4,1924-1935,54,84,9.0,4555,194,60.73,6558+,34.59,16,23,2,202,6,ENG),H Sutcliffe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,1965-1981,74,125,14.0,5357,250,48.26,8662+,49.16,15,33,4,525,23,AUS),KD Walters
58,2002-2014,117,205,13.0,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA),GC Smith
59,1924-1934,29,48,4.0,2122,266,48.22,3118+,44.77,7,6,1,119,0,AUS),WH Ponsford
60,1930-1938,39,62,5.0,2748,232,48.21,3217+,60.02,6,13,4,241,5,AUS),SJ McCabe
61,1928-1934,22,33,6.0,1296,127,48.00,2110+,25.59,1,10,2,53,0,ENG),DR Jardine

In [ ]:
data['highest_score'] = data['highest_score'].str.split(pat = '*').str[0]

In [ ]:
data['highest_score'].astype(int)

0     334
1     269
2     274
3     270
4     194
     ...
57    250
58    277
59    266
60    232
61    127
Name: highest_score, Length: 62, dtype: int64

In [ ]:
data

,year_period,Mat,Inns,Not_Out,Runs,highest_score,Ave,Ball_Faced,Strike_Rate,100,50,0,4s,6s,country,players
0,1928-1948,52,80,10.0,6996,334,99.94,9800+,58.60,29,13,7,626,6,AUS),DG Bradman
1,2015-2016,20,31,7.0,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS),AC Voges
2,1963-1970,23,41,4.0,2256,274,60.97,1707+,54.48,7,11,1,246,11,SA),RG Pollock
3,1930-1954,22,40,4.0,2190,270,60.83,416+,56.00,10,5,2,104,1,WI),GA Headley
4,1924-1935,54,84,9.0,4555,194,60.73,6558+,34.59,16,23,2,202,6,ENG),H Sutcliffe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,1965-1981,74,125,14.0,5357,250,48.26,8662+,49.16,15,33,4,525,23,AUS),KD Walters
58,2002-2014,117,205,13.0,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA),GC Smith
59,1924-1934,29,48,4.0,2122,266,48.22,3118+,44.77,7,6,1,119,0,AUS),WH Ponsford
60,1930-1938,39,62,5.0,2748,232,48.21,3217+,60.02,6,13,4,241,5,AUS),SJ McCabe
61,1928-1934,22,33,6.0,1296,127,48.00,2110+,25.59,1,10,2,53,0,ENG),DR Jardine

# **Making two new columns out of one cloumn**

In [ ]:
data['start_year'] = data['year_period'].str.split(pat = '-').str[0]

In [ ]:
data['end_year'] = data['year_period'].str.split(pat = '-').str[1]

In [ ]:
data

,year_period,Mat,Inns,Not_Out,Runs,highest_score,Ave,Ball_Faced,Strike_Rate,100,50,0,4s,6s,country,players,start_year,end_year
0,1928-1948,52,80,10.0,6996,334,99.94,9800+,58.60,29,13,7,626,6,AUS),DG Bradman,1928,1948
1,2015-2016,20,31,7.0,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS),AC Voges,2015,2016
2,1963-1970,23,41,4.0,2256,274,60.97,1707+,54.48,7,11,1,246,11,SA),RG Pollock,1963,1970
3,1930-1954,22,40,4.0,2190,270,60.83,416+,56.00,10,5,2,104,1,WI),GA Headley,1930,1954
4,1924-1935,54,84,9.0,4555,194,60.73,6558+,34.59,16,23,2,202,6,ENG),H Sutcliffe,1924,1935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,1965-1981,74,125,14.0,5357,250,48.26,8662+,49.16,15,33,4,525,23,AUS),KD Walters,1965,1981
58,2002-2014,117,205,13.0,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA),GC Smith,2002,2014
59,1924-1934,29,48,4.0,2122,266,48.22,3118+,44.77,7,6,1,119,0,AUS),WH Ponsford,1924,1934
60,1930-1938,39,62,5.0,2748,232,48.21,3217+,60.02,6,13,4,241,5,AUS),SJ McCabe,1930,1938
61,1928-1934,22,33,6.0,1296,127,48.00,2110+,25.59,1,10,2,53,0,ENG),DR Jardine,1928,1934

In [ ]:
data.drop(columns=['year_period'], inplace=True)

In [ ]:
data

,Mat,Inns,Not_Out,Runs,highest_score,Ave,Ball_Faced,Strike_Rate,100,50,0,4s,6s,country,players,start_year,end_year
0,52,80,10.0,6996,334,99.94,9800+,58.60,29,13,7,626,6,AUS),DG Bradman,1928,1948
1,20,31,7.0,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS),AC Voges,2015,2016
2,23,41,4.0,2256,274,60.97,1707+,54.48,7,11,1,246,11,SA),RG Pollock,1963,1970
3,22,40,4.0,2190,270,60.83,416+,56.00,10,5,2,104,1,WI),GA Headley,1930,1954
4,54,84,9.0,4555,194,60.73,6558+,34.59,16,23,2,202,6,ENG),H Sutcliffe,1924,1935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,74,125,14.0,5357,250,48.26,8662+,49.16,15,33,4,525,23,AUS),KD Walters,1965,1981
58,117,205,13.0,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA),GC Smith,2002,2014
59,29,48,4.0,2122,266,48.22,3118+,44.77,7,6,1,119,0,AUS),WH Ponsford,1924,1934
60,39,62,5.0,2748,232,48.21,3217+,60.02,6,13,4,241,5,AUS),SJ McCabe,1930,1938
61,22,33,6.0,1296,127,48.00,2110+,25.59,1,10,2,53,0,ENG),DR Jardine,1928,1934

**looking for data type**

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Mat            62 non-null     int64
 1   Inns           62 non-null     int64
 2   Not_Out        62 non-null     float64
 3   Runs           62 non-null     int64
 4   highest_score  62 non-null     object
 5   Ave            62 non-null     float64
 6   Ball_Faced     62 non-null     object
 7   Strike_Rate    62 non-null     float64
 8   100            62 non-null     int64
 9   50             62 non-null     int64
 10  0              62 non-null     int64
 11  4s             62 non-null     int64
 12  6s             62 non-null     int64
 13  country        62 non-null     object
 14  players        62 non-null     object
 15  start_year     62 non-null     object
 16  end_year       62 non-null     object
dtypes: float64(3), int64(8), object(6)
memory usage: 8.4+ KB

# **Correcting data type**

In [ ]:
data['highest_score'] = data['highest_score'].astype(int)

In [ ]:
data['end_year'] = data['end_year'].astype(int)

In [ ]:
data['start_year'] = data['start_year'].astype(int)

In [ ]:
data

,Mat,Inns,Not_Out,Runs,highest_score,Ave,Ball_Faced,Strike_Rate,100,50,0,4s,6s,country,players,start_year,end_year
0,52,80,10.0,6996,334,99.94,9800+,58.60,29,13,7,626,6,AUS),DG Bradman,1928,1948
1,20,31,7.0,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS),AC Voges,2015,2016
2,23,41,4.0,2256,274,60.97,1707+,54.48,7,11,1,246,11,SA),RG Pollock,1963,1970
3,22,40,4.0,2190,270,60.83,416+,56.00,10,5,2,104,1,WI),GA Headley,1930,1954
4,54,84,9.0,4555,194,60.73,6558+,34.59,16,23,2,202,6,ENG),H Sutcliffe,1924,1935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,74,125,14.0,5357,250,48.26,8662+,49.16,15,33,4,525,23,AUS),KD Walters,1965,1981
58,117,205,13.0,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA),GC Smith,2002,2014
59,29,48,4.0,2122,266,48.22,3118+,44.77,7,6,1,119,0,AUS),WH Ponsford,1924,1934
60,39,62,5.0,2748,232,48.21,3217+,60.02,6,13,4,241,5,AUS),SJ McCabe,1930,1938
61,22,33,6.0,1296,127,48.00,2110+,25.59,1,10,2,53,0,ENG),DR Jardine,1928,1934

In [ ]:
# Replace non-digit characters and convert to integer
data['Ball_Faced'] = data['Ball_Faced'].str.split(pat = '+').str[0]

In [ ]:
data['Ball_Faced']

0      9800
1      2667
2      1707
3       416
4      6558
      ...
57     8662
58    15525
59     3118
60     3217
61     2110
Name: Ball_Faced, Length: 62, dtype: object

In [ ]:
data['Ball_Faced'] = data['Ball_Faced'].replace('-', 0).astype('int')

In [ ]:
data['Ball_Faced']

0      9800
1      2667
2      1707
3       416
4      6558
      ...
57     8662
58    15525
59     3118
60     3217
61     2110
Name: Ball_Faced, Length: 62, dtype: int64

In [ ]:
data

,Mat,Inns,Not_Out,Runs,highest_score,Ave,Ball_Faced,Strike_Rate,100,50,0,4s,6s,country,players,start_year,end_year
0,52,80,10.0,6996,334,99.94,9800,58.60,29,13,7,626,6,AUS),DG Bradman,1928,1948
1,20,31,7.0,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS),AC Voges,2015,2016
2,23,41,4.0,2256,274,60.97,1707,54.48,7,11,1,246,11,SA),RG Pollock,1963,1970
3,22,40,4.0,2190,270,60.83,416,56.00,10,5,2,104,1,WI),GA Headley,1930,1954
4,54,84,9.0,4555,194,60.73,6558,34.59,16,23,2,202,6,ENG),H Sutcliffe,1924,1935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,74,125,14.0,5357,250,48.26,8662,49.16,15,33,4,525,23,AUS),KD Walters,1965,1981
58,117,205,13.0,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA),GC Smith,2002,2014
59,29,48,4.0,2122,266,48.22,3118,44.77,7,6,1,119,0,AUS),WH Ponsford,1924,1934
60,39,62,5.0,2748,232,48.21,3217,60.02,6,13,4,241,5,AUS),SJ McCabe,1930,1938
61,22,33,6.0,1296,127,48.00,2110,25.59,1,10,2,53,0,ENG),DR Jardine,1928,1934